# 데이터 불러오기

In [1]:
import numpy as np
import pandas as pd

df = pd.read_csv('Data.csv')

X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

# 결측 데이터 확인


In [4]:
print(df.isnull().sum()) #결측값 2개 확인

Country      0
Age          1
Salary       1
Purchased    0
dtype: int64


# 결측 데이터 처리

In [7]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean') #독립 변수의 평균값으로 처리
X[:, 1:3] = imputer.fit_transform(X[:, 1:3])

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


# 범주형 데이터 인코딩

In [9]:
#독립 변수 인코딩
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
print(X)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [10]:
#종속 변수 인코딩
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

[0 1 0 0 1 1 0 1 0 1]


# train_set, test_set으로 분할하기

In [12]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

# 특성 스케일링

In [14]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train[:, 3:] = sc.fit_transform(X_train[:, 3:])
X_test[:, 3:] = sc.transform(X_test[:, 3:])

[[0.0 0.0 1.0 1.178841189320736 0.9287434145875759]
 [0.0 1.0 0.0 1.2403337943356885 1.3121778914961761]
 [1.0 0.0 0.0 1.4415823198391693 1.57985856405501]
 [-0.816496580927726 -0.5 1.224744871391589 -0.7816226350136118
  -0.7641678152036875]
 [-0.816496580927726 -0.5 1.224744871391589 -0.8467369584257524
  -0.7641998850551783]
 [1.224744871391589 -0.5 -0.816496580927726 -0.7224277955480295
  -0.7641234107939308]
 [-0.816496580927726 2.0 -0.816496580927726 -0.710588827654913
  -0.7641135431473183]
 [1.224744871391589 -0.5 -0.816496580927726 -0.7993810868532866
  -0.7641752159386469]] [[0.0 1.0 0.0 0.7372124805769867 0.9938549295343193]
 [1.0 0.0 0.0 1.089397400208078 1.4170797766881515]]
